trigger:
  tags:
    include:
      - v*

pr: none # disable CI build for PR

resources:
  repositories:
  - repository: BedrockHomebrewCore # The name used to reference this repository in the checkout step
    type: github
    endpoint: "bedrock-cli"
    name: microsoft/homebrew-bedrock

stages:
  - stage: package_build
    jobs:
      - template: azure-pipelines/templates/build-artifacts.yml
        parameters:
          name: Linux
          pool:
            vmImage: ubuntu-16.04

  - stage: github_release
    dependsOn: package_build
    jobs:
      - template: azure-pipelines/templates/create-github-release.yml
        parameters:
          GitHubConnection: "bedrock-cli"
          releaseNotesFilePath: "CHANGELOG.md"
          tagSource: "gitTag" # or "userSpecifiedTag"
          addChangeLog: true
          isDraft: true
  
  - stage: update_homebrew_package
    dependsOn: github_release
    jobs:
      - template: azure-pipelines/templates/update-homebrew-formula.yml
