trigger: none

schedules:
- cron: "0 3 * * *"
  branches:
    include: [ master ] 
  displayName: M-F 7:00PM (UTC - 8:00) Pacific daily build
  always: true

variables:
- group: 'spk-vg'  

stages:
- stage: integration_tests
  jobs:
  - job: "setup_env_and_run_tests"
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'specific'
        project: 'ca459769-cfe0-490c-a89e-1f1eb2eba550'
        definition: '20'
        buildVersionToDownload: 'latestFromBranch'
        branchName: 'refs/heads/master'
        itemPattern: "spk*"
        artifactName: 'spk_linux_node_12'
        targetPath: '$(System.DefaultWorkingDirectory)'
    - bash: |
        shopt -s expand_aliases
        echo "Current Dir is $(pwd)"
        chmod +x spk-linux
        alias spk="$(pwd)/spk-linux"
        spk --version
      displayName: "Verify SPK downloaded and executable"
    - bash: |
        curl $FUNC_SCRIPT > spk-test-func.sh
        chmod +x ./spk-test-func.sh
        curl $TEST_SCRIPT > spk-int.sh
        chmod +x ./spk-int.sh
      displayName: "Download integration test scripts"
      env:
        FUNC_SCRIPT: https://raw.githubusercontent.com/CatalystCode/spk/master/tests/functions.sh
        TEST_SCRIPT: https://raw.githubusercontent.com/CatalystCode/spk/master/tests/validations.sh
    - bash: | 
        # Install the extension
        export AZURE_DEVOPS_EXT_PAT=$(AZDO_PAT)
        az extension add --name azure-devops
        
        # Login to Azure 
        echo "az login --service-principal --username $(SP_APP_ID) --password $(SP_PASS) --tenant $(SP_TENANT)"
        az login --service-principal --username "$(SP_APP_ID)" --password "$(SP_PASS)" --tenant "$(SP_TENANT)"
        
        # Step up git identity
        git config --global user.email "me@microsoft.com"
        git config --global user.name "Service Account"

        #Start Test
        export SPK_PATH="$(pwd)/spk-linux"
        export ACCESS_TOKEN_SECRET=$(AZDO_PAT)

        # Include the functions here
        . ./spk-test-func.sh

        # Run the test
        bash ./spk-int.sh
        status=$?
        [ $status -eq 0 ] && echo "Test Done!" || (echo "Test had issues" && exit 1)
      #failOnStderr: true
      displayName: "Run Tests"

